title: Temitope Alo
logo: ![.](https://github.com/Temitope-Alo/alotemitope.github.io/blob/1d59b745b21a09724e8805eb1056c43818d18dc3/headshot_img.jpg)
Description: Bioinformatics and Data Science portfolio
show_downloads: false
theme: jekyll-theme-minimal
